### ISSUE TITLE
How to compile from source code

### ISSUE THREAD

**Issue by pornwice** [Keelhauled/LockOnPlugin#2]
First at all, thanks for this amazing plugin, it runs smoothly. I also try to add some experimental modification to it, but cannot pass build.

Downloaded Visual Studio, and I noticed this line

https://github.com/Keelhauled/LockOnPlugin/blob/master/LockOnPluginParty/LockOnPluginParty.csproj#L42

```
<HintPath>..\..\DLL\Assembly-CSharp.dll</HintPath>
``` 

I have no idea where the dll file come from, as well as `UnityEngine.dll` and `UnityEngine.UI.dll`. Tried copying dll from `\HoneySelect_64_Data\Managed\`, and that does not work.

**Comment by Keelhauled** [comment]
Sorry for the delay, I don't check github much.
In case you still haven't solved this problem you can just reference your own, clean honey select files from that folder you mentioned. As far as I remember IPA patched files don't work because IPA modifies them.
